server:
  port: 8000

spring:
  application:
    name: Booking-Service

  threads:
    virtual:
      enabled: true


  datasource:
    url: jdbc:postgresql://localhost:5432/airline_reservation_db
    username: tuan
    password: 20226100
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer



services:
  flight:
    url: http://flight-service
  order:
    url: http://order-service
  payment:
    url: http://payment-service
