server:
  port: 8001

spring:
  application:
    name: Booking-Service

  threads:
    virtual:
      enabled: true


  datasource:
    url: ${POSTGRESQL_URL:}
    username: ${POSTGRESQL_USERNAME:}
    password: ${POSTGRESQL_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: booking-group
      enable-auto-commit: true
      properties:
        spring.json.trusted.packages: "*"


domain:
  seat:
    hold-util: PT15M
  ticket:
    hold-util: PT15M


services:
  flight:
    url: http://localhost:8004
  order:
    url: http://localhost:8002
  payment:
    url: http://localhost:8003
