package vn.edu.hust.application.enumeration;

import lombok.Getter;

@Getter
public enum CurrencyUnit {
    AED("United Arab Emirates Dirham", "United Arab Emirates"),
    AFN("Afghan Afghani", "Afghanistan"),
    ALL("Albanian Lek", "Albania"),
    AMD("Armenian Dram", "Armenia"),
    ANG("Netherlands Antillean Guilder", "Netherlands Antilles"),
    AOA("Angolan Kwanza", "Angola"),
    ARS("Argentine Peso", "Argentina"),
    AUD("Australian Dollar", "Australia"),
    AWG("Aruban Florin", "Aruba"),
    AZN("Azerbaijani Manat", "Azerbaijan"),
    BAM("Bosnia-Herzegovina Convertible Mark", "Bosnia and Herzegovina"),
    BBD("Barbadian Dollar", "Barbados"),
    BDT("Bangladeshi Taka", "Bangladesh"),
    BGN("Bulgarian Lev", "Bulgaria"),
    BHD("Bahraini Dinar", "Bahrain"),
    BIF("Burundian Franc", "Burundi"),
    BMD("Bermudan Dollar", "Bermuda"),
    BND("Brunei Dollar", "Brunei"),
    BOB("Bolivian Boliviano", "Bolivia"),
    BRL("Brazilian Real", "Brazil"),
    BSD("Bahamian Dollar", "Bahamas"),
    BTC("Bitcoin", "Global"),
    BTN("Bhutanese Ngultrum", "Bhutan"),
    BWP("Botswanan Pula", "Botswana"),
    BYN("New Belarusian Ruble", "Belarus"),
    BYR("Belarusian Ruble", "Belarus"),
    BZD("Belize Dollar", "Belize"),
    CAD("Canadian Dollar", "Canada"),
    CDF("Congolese Franc", "Democratic Republic of the Congo"),
    CHF("Swiss Franc", "Switzerland"),
    CLF("Chilean Unit of Account (UF)", "Chile"),
    CLP("Chilean Peso", "Chile"),
    CNY("Chinese Yuan", "China"),
    CNH("Chinese Yuan Offshore", "China"),
    COP("Colombian Peso", "Colombia"),
    CRC("Costa Rican Colón", "Costa Rica"),
    CUC("Cuban Convertible Peso", "Cuba"),
    CUP("Cuban Peso", "Cuba"),
    CVE("Cape Verdean Escudo", "Cape Verde"),
    CZK("Czech Republic Koruna", "Czech Republic"),
    DJF("Djiboutian Franc", "Djibouti"),
    DKK("Danish Krone", "Denmark"),
    DOP("Dominican Peso", "Dominican Republic"),
    DZD("Algerian Dinar", "Algeria"),
    EGP("Egyptian Pound", "Egypt"),
    ERN("Eritrean Nakfa", "Eritrea"),
    ETB("Ethiopian Birr", "Ethiopia"),
    EUR("Euro", "Eurozone"),
    FJD("Fijian Dollar", "Fiji"),
    FKP("Falkland Islands Pound", "Falkland Islands"),
    GBP("British Pound Sterling", "United Kingdom"),
    GEL("Georgian Lari", "Georgia"),
    GGP("Guernsey Pound", "Guernsey"),
    GHS("Ghanaian Cedi", "Ghana"),
    GIP("Gibraltar Pound", "Gibraltar"),
    GMD("Gambian Dalasi", "Gambia"),
    GNF("Guinean Franc", "Guinea"),
    GTQ("Guatemalan Quetzal", "Guatemala"),
    GYD("Guyanaese Dollar", "Guyana"),
    HKD("Hong Kong Dollar", "Hong Kong"),
    HNL("Honduran Lempira", "Honduras"),
    HRK("Croatian Kuna", "Croatia"),
    HTG("Haitian Gourde", "Haiti"),
    HUF("Hungarian Forint", "Hungary"),
    IDR("Indonesian Rupiah", "Indonesia"),
    ILS("Israeli New Sheqel", "Israel"),
    IMP("Manx pound", "Isle of Man"),
    INR("Indian Rupee", "India"),
    IQD("Iraqi Dinar", "Iraq"),
    IRR("Iranian Rial", "Iran"),
    ISK("Icelandic Króna", "Iceland"),
    JEP("Jersey Pound", "Jersey"),
    JMD("Jamaican Dollar", "Jamaica"),
    JOD("Jordanian Dinar", "Jordan"),
    JPY("Japanese Yen", "Japan"),
    KES("Kenyan Shilling", "Kenya"),
    KGS("Kyrgystani Som", "Kyrgyzstan"),
    KHR("Cambodian Riel", "Cambodia"),
    KMF("Comorian Franc", "Comoros"),
    KPW("North Korean Won", "North Korea"),
    KRW("South Korean Won", "South Korea"),
    KWD("Kuwaiti Dinar", "Kuwait"),
    KYD("Cayman Islands Dollar", "Cayman Islands"),
    KZT("Kazakhstani Tenge", "Kazakhstan"),
    LAK("Laotian Kip", "Laos"),
    LBP("Lebanese Pound", "Lebanon"),
    LKR("Sri Lankan Rupee", "Sri Lanka"),
    LRD("Liberian Dollar", "Liberia"),
    LSL("Lesotho Loti", "Lesotho"),
    LTL("Lithuanian Litas", "Lithuania"),
    LVL("Latvian Lats", "Latvia"),
    LYD("Libyan Dinar", "Libya"),
    MAD("Moroccan Dirham", "Morocco"),
    MDL("Moldovan Leu", "Moldova"),
    MGA("Malagasy Ariary", "Madagascar"),
    MKD("Macedonian Denar", "North Macedonia"),
    MMK("Myanma Kyat", "Myanmar"),
    MNT("Mongolian Tugrik", "Mongolia"),
    MOP("Macanese Pataca", "Macau"),
    MRU("Mauritanian Ouguiya", "Mauritania"),
    MUR("Mauritian Rupee", "Mauritius"),
    MVR("Maldivian Rufiyaa", "Maldives"),
    MWK("Malawian Kwacha", "Malawi"),
    MXN("Mexican Peso", "Mexico"),
    MYR("Malaysian Ringgit", "Malaysia"),
    MZN("Mozambican Metical", "Mozambique"),
    NAD("Namibian Dollar", "Namibia"),
    NGN("Nigerian Naira", "Nigeria"),
    NIO("Nicaraguan Córdoba", "Nicaragua"),
    NOK("Norwegian Krone", "Norway"),
    NPR("Nepalese Rupee", "Nepal"),
    NZD("New Zealand Dollar", "New Zealand"),
    OMR("Omani Rial", "Oman"),
    PAB("Panamanian Balboa", "Panama"),
    PEN("Peruvian Nuevo Sol", "Peru"),
    PGK("Papua New Guinean Kina", "Papua New Guinea"),
    PHP("Philippine Peso", "Philippines"),
    PKR("Pakistani Rupee", "Pakistan"),
    PLN("Polish Zloty", "Poland"),
    PYG("Paraguayan Guarani", "Paraguay"),
    QAR("Qatari Rial", "Qatar"),
    RON("Romanian Leu", "Romania"),
    RSD("Serbian Dinar", "Serbia"),
    RUB("Russian Ruble", "Russia"),
    RWF("Rwandan Franc", "Rwanda"),
    SAR("Saudi Riyal", "Saudi Arabia"),
    SBD("Solomon Islands Dollar", "Solomon Islands"),
    SCR("Seychellois Rupee", "Seychelles"),
    SDG("South Sudanese Pound", "South Sudan"),
    SEK("Swedish Krona", "Sweden"),
    SGD("Singapore Dollar", "Singapore"),
    SHP("Saint Helena Pound", "Saint Helena"),
    SLE("Sierra Leonean Leone", "Sierra Leone"),
    SLL("Sierra Leonean Leone", "Sierra Leone"),
    SOS("Somali Shilling", "Somalia"),
    SRD("Surinamese Dollar", "Suriname"),
    STD("São Tomé and Príncipe Dobra", "São Tomé and Príncipe"),
    SVC("Salvadoran Colón", "El Salvador"),
    SYP("Syrian Pound", "Syria"),
    SZL("Swazi Lilangeni", "Eswatini"),
    THB("Thai Baht", "Thailand"),
    TJS("Tajikistani Somoni", "Tajikistan"),
    TMT("Turkmenistani Manat", "Turkmenistan"),
    TND("Tunisian Dinar", "Tunisia"),
    TOP("Tongan Paʻanga", "Tonga"),
    TRY("Turkish Lira", "Turkey"),
    TTD("Trinidad and Tobago Dollar", "Trinidad and Tobago"),
    TWD("New Taiwan Dollar", "Taiwan"),
    TZS("Tanzanian Shilling", "Tanzania"),
    UAH("Ukrainian Hryvnia", "Ukraine"),
    UGX("Ugandan Shilling", "Uganda"),
    USD("United States Dollar", "United States"),
    UYU("Uruguayan Peso", "Uruguay"),
    UZS("Uzbekistan Som", "Uzbekistan"),
    VEF("Venezuelan Bolívar Fuerte", "Venezuela"),
    VES("Sovereign Bolivar", "Venezuela"),
    VND("Vietnamese Dong", "Vietnam"),
    VUV("Vanuatu Vatu", "Vanuatu"),
    WST("Samoan Tala", "Samoa"),
    XAF("CFA Franc BEAC", "CFA Franc BEAC Countries"),
    XAG("Silver (troy ounce)", "Global"),
    XAU("Gold (troy ounce)", "Global"),
    XCD("East Caribbean Dollar", "East Caribbean States"),
    XDR("Special Drawing Rights", "Global"),
    XOF("CFA Franc BCEAO", "CFA Franc BCEAO Countries"),
    XPF("CFP Franc", "French Pacific Territories"),
    YER("Yemeni Rial", "Yemen"),
    ZAR("South African Rand", "South Africa"),
    ZMK("Zambian Kwacha (pre-2013)", "Zambia"),
    ZMW("Zambian Kwacha", "Zambia"),
    ZWL("Zimbabwean Dollar", "Zimbabwe");

    private final String fullName;
    private final String nation;

    CurrencyUnit(String fullName, String nation) {
        this.fullName = fullName;
        this.nation = nation;
    }

    public static CurrencyUnit getCurrencyUnitByNation(String nationName) {
        try {
            EurozoneNation.valueOf(nationName.toUpperCase().replace(" ", "_"));
            return CurrencyUnit.EUR;
        } catch (IllegalArgumentException _) {
            try {
                UsdNation.valueOf(nationName.toUpperCase().replace(" ", "_"));
                return CurrencyUnit.USD;
            } catch (IllegalArgumentException _) {
                for (CurrencyUnit unit : CurrencyUnit.values()) {
                    if (unit.getNation().equalsIgnoreCase(nationName)) {
                        return unit;
                    }
                }
            }
        }
        return CurrencyUnit.USD;
    }
}